# Generated by Django 2.2 on 2021-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coreMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deep', models.IntegerField(default=0)),
                ('Sneha', models.IntegerField(default=0)),
                ('Praveen', models.IntegerField(default=0)),
                ('Akshay', models.IntegerField(default=0)),
                ('Somin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
            ],
        ),
    ]
