# Generated by Django 2.2 on 2021-08-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coreMembers',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
